[project]
name = "spacepp"
version = "1.1.0"
author = "Quan Zhou"
description = "Space++ macOS 键盘快捷键增强工具"
readme = "README.md"
requires-python = ">=3.6"
dependencies = [
  "pyobjc-core>=8.0.0",
  "pyobjc-framework-Cocoa>=8.0.0",
  "pyobjc-framework-Quartz>=8.0.0",
  "pyobjc-framework-ScriptingBridge>=8.0.0",
  "py2app",
  "pyinstaller",
]

[tool.uv]
