"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = [
    'config.json',
    ('icons', ['icons/hyper_icon.svg', 'icons/idle_icon.svg'])
]
OPTIONS = {
    'argv_emulation': True,
    'site_packages': True,
    'plist': {
        'LSUIElement': True,
    },
    'frameworks': ['/Users/bytedance/miniconda3/lib/libffi.8.dylib'],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)